version: '3'

services:
  redis:
    image: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/blitz_api 
    command: poetry run gunicorn --bind 0.0.0.0:5000 blitz_api:create_app\(\)
    expose: 
      - 5000
    #ports:
    #- 5000:80

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/blitz_api
    command: poetry run celery -A make_celery worker --loglevel=info -P threads
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - web
