version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 1337:80

